### ISSUE TITLE
Update UUIDUtil to accommodate new Android ScanRecord impl

### ISSUE THREAD

**Issue by dariuszseweryn** [dariuszseweryn/RxAndroidBle#593]
### Summary
Android's `android.bluetooth.le.ScanRecord#parseFromBytes` has changed between versions. `com.polidea.rxandroidble2.internal.util.UUIDUtil#parseFromBytes` function is not up-to-date with the implementation. This causes inconsistencies.

Additionally Android's native implementations also differ when wrapped by the library

### Library version
`1.10.0`

### Preconditions
Scan a peripheral that advertises data not parsable by Android <8.0 i.e. Service Data with UUIDs longer than 16 bits

#### Steps to reproduce actual result
<br />1. Take a phone that uses Android 4.3<x<8.0 and Android >=8.0
<br />2. Run BLE scan using the new API
<br />3. Observe inconsistencies in `ScanResult#getServiceData` if the service UUID is longer than 16 bits

#### Actual result
Inconsistencies. On Android <8.0 the `ScanResult#getServiceData()` can return an empty map where on Android 8.0 it will contain entries

#### Expected result
On all Android system versions `ScanResult#getServiceData()` should return the same non-empty data

**Comment by nrbrook** [comment]
Fixed in https://github.com/Polidea/RxAndroidBle/pull/711
