### ISSUE TITLE
are we support Extended Advertising scanning?

### ISSUE THREAD

**Issue by shiguiyuan** [dariuszseweryn/RxAndroidBle#774]
**when doing ble scan, I'm always get Legacy adv packets only?**
if I wana get extended advertising packets, any extra operations needs to be done? or this is unsupported feature?

**Comment by dariuszseweryn** [comment]
Hi, if this is still relevant — would you like to elaborate?

**Comment by dariuszseweryn** [comment]
Should be covered in 1.16.0.
