### ISSUE TITLE
BLE Gatt exception link desperately out of date

### ISSUE THREAD

**Issue by ariccio** [dariuszseweryn/RxAndroidBle#778]
**Describe the bug**
[The URL](https://github.com/dariuszseweryn/RxAndroidBle/blob/da9dcf1e9de3e722a25b86d44c59dc9444dcb6b6/rxandroidble/src/main/java/com/polidea/rxandroidble2/exceptions/BleGattException.java#L14) that is (very very helpfully) displayed to suggest looking up the internal android GATT error codes is desperately out of date. I love that you're doing this, it puts a smile on my face, but 7 years is a bit old, to the point that it's harder to make sense of what's going on.

**To Reproduce**

**Expected behavior**
A somewhat recent version of the android platform :)

Nowadays google has ported their awesome chromium code search tool over to other projects. I can find an up-to-date list of `GattStatus` here: https://cs.android.com/android/platform/superproject/+/master:packages/modules/Bluetooth/system/stack/include/gatt_api.h;l=37;bpv=1;bpt=1

The error (`GATT_ERROR` really?) I saw was of course totally non-descript and not your fault. But hey, someone might benefit from an up-to-date version.

Lemme see if I can spin up a PR.

**Smartphone (please complete the following information):**
 - Device: I'm using a Pixel XL. Yes, it's on it's last legs!
 - This code is in `main` right now.

**Comment by dariuszseweryn** [comment]
This you have fixed yourself. Thank you.
