### ISSUE TITLE
Android 12 -android:usesPermissionFlags Not Found - Android resource linking failed

### ISSUE THREAD

**Issue by vijayalakshmi582356** [dariuszseweryn/RxAndroidBle#784]
**build.gradle:**

compileSdkVersion 32
buildToolsVersion "32.1.0-rc1"
minSdkVersion 21
targetSdkVersion 32

**AndroidManifest.xml**

<uses-permission android:name="android.permission.BLUETOOTH_SCAN"
 android:usesPermissionFlags="neverForLocation"
 tools:targetApi="s" />

For me, Assemble fails with error "Android resource linking failed" - AAPT: error: attribute android:usesPermissionFlags not found.
Please let me know if you know how to fix this error. 

Thanks in advance and looking forward to your help.

**Comment by dariuszseweryn** [comment]
Check if you can compile the sample application. For me it seems to work so I think it should work for you as well

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
