### ISSUE TITLE
Investigate: Android 12, BLUETOOTH_CONNECT & getBondedDevices()

### ISSUE THREAD

**Issue by dariuszseweryn** [dariuszseweryn/RxAndroidBle#788]
As hinted in #768 — on Android 12 there apparently is a need to have BLUETOOTH_CONNECT permission when calling RxBleClient.getBondedDevices().

If you, the reader, have an Android 12 device and you're willing to help and check — please do.

If that is the case update Javadocs.

**Comment by DaBs** [comment]
Hi Darius, I made the original PR that I can see you've merged now, and that seems to be entirely correct based on what we can see of usage.

How should we go about it from here?

**Comment by dariuszseweryn** [comment]
@DaBs I am thinking whether there should be a separate library exception or is the system one just fine, especially that this API is synchronous

**Comment by DaBs** [comment]
@dariuszseweryn I think system error should be fine honestly - getting the error is clear and concise.

**Comment by dariuszseweryn** [comment]
I have added that info to Javadoc and left the feature as it is. Thanks for the opinion!
