### ISSUE TITLE
Establish connection trigger Pairing/Bond request every time at every session on Android 13

### ISSUE THREAD

**Issue by datsuk000** [dariuszseweryn/RxAndroidBle#809]
In our BT device, the BLE pairing request is triggered when the client(app) is trying to access the "write" characteristic, but I noticed that `rxBleDevice?.establishConnection(false)` triggered it much faster and it appears every app session with Android 13. Do you know what can trigger it? And if yes, how I can avoid it at the beginning?

**Comment by dariuszseweryn** [comment]
Usually bonding request is issued automatically whenever the peripheral requests bonding or the app will get an "unauthorised access" status code.
In earlier versions of Android it was possible to hijack system intents for bluetooth bonding but I am unsure if this is still possible.

**Comment by datsuk000** [comment]
Thanks for the answer. Maybe you have some references where it is possible to look at how to implement this workaround?

**Comment by dariuszseweryn** [comment]
Check Wiki FAQ for bonding

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
