### ISSUE TITLE
Production build crash for RxBleLog

### ISSUE THREAD

**Issue by e-Joe** [dariuszseweryn/RxAndroidBle#811]
## :bomb: Steps to reproduce

1. Add custom log in RxBleClient.updateLogOptions
```
        RxBleClient.updateLogOptions(
            LogOptions.Builder()
                .setLogLevel(LogConstants.VERBOSE)
                .setMacAddressLogSetting(LogConstants.MAC_ADDRESS_FULL)
                .setUuidsLogSetting(LogConstants.UUIDS_FULL)
                .setShouldLogScannedPeripherals(true)
                .setShouldLogAttributeValues(true)
                .setLogger(MyAppBleLogger())
                .build()
        )
```  
2. Enable proguard in gradle build for production  It works well with debug build type .
3. When I try some BLE operation I am getting error => **Synthetic stacktrace didn't have enough elements: are you using proguard?**  Please check report from Firebase.
    

[RxBleLog crahs.txt](https://github.com/dariuszseweryn/RxAndroidBle/files/9617237/RxBleLog.crahs.txt)

**Comment by dariuszseweryn** [comment]
Hello!
Thank you for using the lib and for the report. This is indeed a bug. I will work on it.

**Comment by dariuszseweryn** [comment]
Could you try out 1.16.1-SNAPSHOT release and report if that fixes the issue you encountered?
Instructions how to integrate snapshot repositories are [here](https://github.com/dariuszseweryn/RxAndroidBle#snapshot).

**Comment by dariuszseweryn** [comment]
@e-Joe — any chance of you testing the snapshot release?
