### ISSUE TITLE
Got no connection errors when using autoconnect: true

### ISSUE THREAD

**Issue by danielRi** [dariuszseweryn/RxAndroidBle#812]
This might be a misconception by me.

We noticed when we use autoconnect: true our Observable chain does not get any error callbacks when we are connecting. We have the following problem: We want to always reconnect as quickly as possible when connection is disrupted, however when the user connects the first time (with an action, like a button click), we want to show an error first and let him connect again.

```
rxBleDevice.establishConnection(true)
       .retryWhen { errorObservable ->
            return errorObservable.flatMap { error ->
               // we only get errors here with autoconnect: false, not true

               // decied to retry etc...
               return@flatMap Observable.error<RxBleConnection>(error)
            }
       }
```
Now it's already mentioned autoconnect might be confusing. From what I understand the problem is that the establishConnection never emits a connection observable, because a connection is never established.
Is there a way to handle errors that happen before a connection is created?

Note: The error occuring is not important for me here, Im only concerned about handling errors (before a connection is established)

**Comment by dariuszseweryn** [comment]
What errors are you expecting?

**Comment by danielRi** [comment]
GATT_ERROR 133, when I remove the battery from the device while connecting.

**Comment by dariuszseweryn** [comment]
You probably won't get it when using autocorrect as the Android will continue until connection is successfully made

**Comment by dariuszseweryn** [comment]
If you want to have a 30 second timeout then you should use `autoconnect=false`. 
Why do you want to use `autoconnect=true`?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
