### ISSUE TITLE
Refresh list Characteristic

### ISSUE THREAD

**Issue by ThuanNH4** [dariuszseweryn/RxAndroidBle#816]
hi Darius, 
I have a question
When i make 1 request to change mode to my device, my device already changed mode (new characteristic has been added) but then i make 1 request to read data from that new characteristic, I got the exception com.polidea.rxandroidble2.exceptions.Ble CharacteristicNotFoundException: No trait found with UUID xxx
I think I will need send a refresh request to my device before reading, can you guide me how to refresh the current list Characteristic?

**Comment by dariuszseweryn** [comment]
[Would this help](https://github.com/dariuszseweryn/RxAndroidBle/pull/453#issuecomment-459787554)?

**Comment by ThuanNH4** [comment]
Exactly, let me check. 
Thank you
