### ISSUE TITLE
how can i get writeCharacteristic response?

### ISSUE THREAD

**Issue by 857288218** [dariuszseweryn/RxAndroidBle#817]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dariuszseweryn** [comment]
subscribe to `Single<byte[]> RxBleConnection#writeCharacteristic(UUID)`. If you do not know what is a Single or a subscribe is google for RxJava introduction.
