### ISSUE TITLE
Permission for connection with sample-kotlin

### ISSUE THREAD

**Issue by SeigiTenshi** [dariuszseweryn/RxAndroidBle#822]
Hi,

I use yours sample-kotlin to try understand how to code with your library but I face an issues.
The scan work perfectly fine but when I try "service discovery" I have this message : "Connection error: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNEC..."
I had "uses-permission android:name="android.permission.BLUETOOTH_CONNECT " in AndroidManifest.xml but the issue is the same.

My mobile is an OppoReno 6 5g with 12 android version

Thanks for any help you can provide

**Comment by dariuszseweryn** [comment]
Hmmm... I see that there is a problem in the sample app and the library. You should be able to workaround it by giving a `BLUETOOTH_CONNECT` runtime permission to the app.

**Comment by SeigiTenshi** [comment]
Thanks I was able to fix it with the runtime permission it's work perfectly fine now
