### ISSUE TITLE
Does RxAndroidBle support the use of Bluetooth Gatt's connect method? 

### ISSUE THREAD

**Issue by stylsw** [dariuszseweryn/RxAndroidBle#826]
Does RxAndroidBle support the use of Bluetooth Gatt's connect method? And can I know the callback result of the connect method?

**Comment by dariuszseweryn** [comment]
`RxBleDevice.establishConnection` calls `connectGatt` under the hood. If the status != GATT_SUCCESS then an exception is being emitted from the observable. That exception contains the exact status.

**Comment by stylsw** [comment]
support the use of BluetoothGatt.connect()?

**Comment by stylsw** [comment]
I want to use BluetoothGatt.connect() when there is an instance of a BluetoothGatt object. What should I do?

**Comment by dariuszseweryn** [comment]
You can't and that is per the design of this library. `BluetoothGatt.connect()` has some undocumented behaviour which makes its usage non-trivial. Additionally the library cannot work if it does not have access to `BluetoothGattCallbacks` and passing an existing `BluetoothGatt` prevents from registering more callbacks.

Anyway — why would you want to use `BluetoothGatt.connect()`? What is your use-case?
