### ISSUE TITLE
scanResult.bleDevice.name not showing Ble updated name

### ISSUE THREAD

**Issue by naveedhanif300** [dariuszseweryn/RxAndroidBle#830]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 10]
 - Library version: [e.g. 1.10.5]

**Logs from the application when bug occurs (this will greatly help in quick understanding the problem)**
To turn on logs use:
```
RxBleClient.updateLogOptions(new LogOptions.Builder()
        .setLogLevel(LogConstants.DEBUG)
        .setMacAddressLogSetting(LogConstants.MAC_ADDRESS_FULL)
        .setUuidsLogSetting(LogConstants.UUIDS_FULL)
        .setShouldLogAttributeValues(true)
        .build()
);
```
```
// please paste the logs here
```

**Additional context**

**Comment by dariuszseweryn** [comment]
The `RxBleDevice.getName()` calls `BluetoothDevice.getName()` under the hood. It returns the same what Android OS returns.
