### ISSUE TITLE
BLUETOOTH_SCAN set usesPermissionFlags="neverForLocation"，Is there a problem？

### ISSUE THREAD

**Issue by stylsw** [dariuszseweryn/RxAndroidBle#831]
Note: If you include neverForLocation in your android:usesPermissionFlags, some BLE beacons are filtered from the scan results.

**Comment by dariuszseweryn** [comment]
That is correct as beacons may be used for location — no?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
