### ISSUE TITLE
GenericFailure<CharacteristicValueUpdateError>

### ISSUE THREAD

**Issue by qq1023308356** [dariuszseweryn/RxAndroidBle#832]
Exception: GenericFailure<CharacteristicValueUpdateError>(code: CharacteristicValueUpdateError.unknown, message: "Cannot write client characteristic config descriptor (code 3) with characteristic UUID 6e400003-b5a3-f393-e0a9-e50e24dcca9e")

**Comment by qq1023308356** [comment]
After the appearance, all reading and writing services are invalid, and it is useless to restart app. Need to restart the phone to be normal

**Comment by dariuszseweryn** [comment]
Hello
Unfortunately your bug report does not provide much actionable information — could you conform to the template?

**Comment by qq1023308356** [comment]
This problem is because the device switched UUID, and then when reading and writing, it took the previous UUID,clearGattCache this method is useless, bluetoothGatt there is no refresh method in it. set it to turn Bluetooth back on and it will return to normal. do you have any good solutions here?

**Comment by qq1023308356** [comment]
https://github.com/dariuszseweryn/RxAndroidBle/issues/692
Should be similar to this question

**Comment by qq1023308356** [comment]
@dariuszseweryn

**Comment by dariuszseweryn** [comment]
Hello, there is a wiki page about custom operations [one of which allows for gatt refresh](https://github.com/dariuszseweryn/RxAndroidBle/wiki/Tutorial:-RxBleCustomOperation#call-vanilla-api-refresh-method-by-reflection). You can then use the next operation to discover services once more an use them accordingly. I did not had an opportunity to work with devices that change services so you need to figure out the details

**Comment by qq1023308356** [comment]
@dariuszseweryn 
BluetoothGatt.refresh() This method is invalid.
Discover services bypassing library cache，How to use？

**Comment by dariuszseweryn** [comment]
> BluetoothGatt.refresh() This method is invalid.

Calls using reflection don't work anymore?

> Discover services bypassing library cache，How to use？

Custom operation on the client

**Comment by qq1023308356** [comment]
> > BluetoothGatt.refresh() This method is invalid.
> 
> Calls using reflection don't work anymore?
> 
> > Discover services bypassing library cache，How to use？
> 
> Custom operation on the client

Yes, the error report did not find this method.

**Comment by dariuszseweryn** [comment]
Could you share logs?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
