### ISSUE TITLE
Send long bytes  twice 

### ISSUE THREAD

**Issue by wudouxingjun** [dariuszseweryn/RxAndroidBle#835]
**Describe the bug**
send long bytes twice but throw BleAlreadyConnectedException

**To Reproduce**
1. Go to LongwriteActivity
2. Click on SendButton
3. Click on SendButton Again
4. See error   throw BleAlreadyConnectedException

**Expected behavior**
not throw BleAlreadyConnectedException

**Logs from the application when bug occurs (this will greatly help in quick understanding the problem)**
To turn on logs use:
```
observable = bleDevice.establishConnection(true);
flatMap = observable.flatMap(rxBleConnection -> rxBleConnection.createNewLongWriteBuilder()
                                                .setCharacteristicUuid(characteristicUuid) // required or the .setCharacteristic()
                                                // .setCharacteristic() alternative if you have a specific BluetoothGattCharacteristic
                                                .setBytes(bytesToWrite)
                                                // .setWriteOperationRetryStrategy(retryStrategy) // if you'd like to retry batch write operations on failure, provide your own retry strategy
                                                // .setMaxBatchSize(maxBatchSize) // optional -> default 20 or current MTU
                                                // .setWriteOperationAckStrategy(ackStrategy) // optional to postpone writing next batch
                                                .build()
                                        );
 flatMap.subscribe(
                        byteArray -> {
                            // Written data.
                            Log.d("Longwrite", "bytes.length = " + byteArray.length);
                        },
                        throwable -> {
                            // Handle an error here.
                            Log.d("Longwrite", "throwable.getMessage()" + throwable.getMessage());
                        }
                );
```
```
// please paste the logs here
```

**Additional context**
![image](https://github.com/dariuszseweryn/RxAndroidBle/assets/10608014/5b739f47-f614-4098-9bec-68d5d29a4b03)

**Comment by dariuszseweryn** [comment]
Hello @wudouxingjun 
Thanks for using the library. Since `LongWriteExampleActivity` does not have any layout set — how did you wire that activity? The code you pasted is from Readme, not the activity.
Would [typical resolutions work](https://github.com/dariuszseweryn/RxAndroidBle/wiki/Tutorial:-Connection-Observable-sharing) for you?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
