### ISSUE TITLE
Write request is not processed in the random order

### ISSUE THREAD

**Issue by shellyb985** [dariuszseweryn/RxAndroidBle#836]
**Describe the bug**
Write data to multiple characteristics one by one and I dont want to wait for response of each write. Problem here is Order of write not executed same as I requested.

**To Reproduce**
Writing the data to multiple characteristic one by one.
rxBleConnection.writeCharacteristic(characteristicUUID1, bytesToWrite))
rxBleConnection.writeCharacteristic(characteristicUUID2, bytesToWrite))
rxBleConnection.writeCharacteristic(characteristicUUID3, bytesToWrite))
rxBleConnection.writeCharacteristic(characteristicUUID4, bytesToWrite))

When I print the logs, write is executed in the different order
ie,
1st  characteristicUUID3 - executed
2nd characteristicUUID2 - executed
3rd characteristicUUID4 - executed
4th characteristicUUID1 - executed

**Expected behavior**
I am expecting write should occur in the same order as my request.
like in below order, 
1st  characteristicUUID1 - executed
2nd characteristicUUID2 - executed
3rd characteristicUUID3 - executed
4th characteristicUUID4 - executed

**Comment by dariuszseweryn** [comment]
Hello, thanks for using the library. I am afraid that without a code sample I cannot recreate your issue. Writes (and most of other interactions) are handled in FIFO order by default. Could you share more details?

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
