### ISSUE TITLE
Is the library still maintained? 

### ISSUE THREAD

**Issue by arbonvata** [dariuszseweryn/RxAndroidBle#842]
The last release is almost one year old. Can't see much activity in the repo

**Comment by dariuszseweryn** [comment]
Hello! 
While I do not have much time for maintenance nor I actively use the library — I try to address issues as they come and merge PRs. Do you have any specific needs?

**Comment by arbonvata** [comment]
Actually it is more to see if we can use it our projects. Many ble libraries becomes obsolete with time due to lack of updates and breaking changes from google :)

**Comment by dariuszseweryn** [comment]
I _hope_ this library will be obsolete because google would step-up and create an extension with a nice API support for older OS versions. Recently a [bluetooth Jetpack library](https://developer.android.com/jetpack/androidx/releases/bluetooth) was released, so 🤞.
