### ISSUE TITLE
Metode readcharacteristic not stream

### ISSUE THREAD

**Issue by arbaelbarca** [dariuszseweryn/RxAndroidBle#845]
Hello my names is arba, currently i used library this, but when the use readcharacteristic, its not working type stream,

maybe anyone helping me

**Comment by dariuszseweryn** [comment]
Hello,
Thanks for using the library. I am unsure if I understand your question:
Do you expect that reading a characteristic would return a stream of values?
If so you probably want to `RxBleConnection#setupNotifications`

**Comment by dariuszseweryn** [comment]
Closing due to lack of information and inactivity of the original poster.

When more data will be available—feel free to add that information and reopen this issue.

Best Regards
