### ISSUE TITLE
Can't scan after connect dispose/clear

### ISSUE THREAD

**Issue by riokang** [dariuszseweryn/RxAndroidBle#852]
**Describe the bug**

I am connecting to ble device using rxandroidble2.

After successful connection to the device, I'm testing reconnection after forcibly terminating the connection.

Although the disposible for the connection has been disposed, the device does not switch to the advertise state.

Only when turn off the screen of cell phone will the ble device switch to advertised state and scanning will be possible.

Is there a way to make sure the code disconnects from the BLE device?

Below is my viewmodel code.

**Smartphone (please complete the following information):**
 - Device: Galaxy S20 5G
 - OS: android13
 - Library version: rxandroidble:1.11.1

**Logs from the application when bug occurs (this will greatly help in quick understanding the problem)**
To turn on logs use:
```
public void doOnDeviceSelectPage() throws Exception {
        if (rxBleClient == null) {
            initRxBleClient();
            return;
        }

        if (disposable.isDisposed()) {
            disposable = new CompositeDisposable();
        }


        disposable.add(
                onDeviceSelectPageBleUseCase.execute(rxBleClient)
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(
                                rxBleConnectionPair -> {
                                    ScanResult scanResult = rxBleConnectionPair.first;
                                    RxBleConnection rxBleConnection = rxBleConnectionPair.second;
                                    String scannedDevice = new String(scanResult.getScanRecord().getManufacturerSpecificData(0xffff));

                                    // Handle each scan result
                                    Log.d("BleConnect", "Device connect: " + scannedDevice);

                                   
                                    onDeviceConnected();
                                    if (scannedDevice.equals("A")) {
                                        deviceController.setRxBleConnection(rxBleConnection);
                                        deviceController.onDeviceConnected();
                                    } 
                                },
                                throwable -> {
//                                    onDeviceDisconnected();
                                    // Handle errors
                                    Log.e("BleScan", "Error: " + throwable.getMessage());
                                    onDeviceDisconnected();
                                }
                        )
        );
    }


    public void onDeviceDisconnected() throws Exception {
        setConnectedDevice(null);

        disposable.dispose();
    }

}
```
```
// please paste the logs here
```

**Additional context**

**Comment by dariuszseweryn** [comment]
Hello, thanks for using the library!

Unfortunately you have not provided logs and most of the relevant information about the RxJava flow is lacking from the code you posted so I cannot really help without more info. Anyway for now it seems to be a coding error and not a bug in the library so we can continue in [this StackOverflow topic](https://stackoverflow.com/questions/78216950/cant-scan-after-connect-dispose-clear) so it will be easier to discover by others.

Best regards
