### ISSUE TITLE
Add `advertisingSid` property to `ScanResult` and `RxBleInternalScanResult`

### ISSUE THREAD

**Issue by KrzysztofMamak** [dariuszseweryn/RxAndroidBle#854]
**Is your feature request related to a problem? Please describe.**
`com.polidea.rxandroidble2.scan.ScanResult` does not contain an information about advertising sid which is needed for supporting Bluetooth Auracast feature (https://www.bluetooth.com/wp-content/uploads/Files/Specification/HTML/24670-BASS-html5/out/en/index-en.html#UUID-2a17a3a2-36f9-8cb4-0877-3b56055a7955). It means that there is no option to retrieve this information from the `rxandroidble` library.

**Describe the solution you'd like**
`com.polidea.rxandroidble2.scan.ScanResult` and `com.polidea.rxandroidble2.internal.scan.RxBleInternalScanResult` classes can be extended with `advertisingSid` property. This value can be retrieved using `android.bluetooth.le.ScanResult.getAdvertisingSid` method (https://developer.android.com/reference/kotlin/android/bluetooth/le/ScanResult#getadvertisingsid) and propagated in `com.polidea.rxandroidble2.internal.scan.InternalScanResultCreator`.

I can volunteer and submit a PR soon.

**Comment by dariuszseweryn** [comment]
Hey, sorry for a long pause, got a busy time at work. Feel free to open a PR 👍

**Comment by KrzysztofMamak** [comment]
I'll open a PR soon.

**Comment by dariuszseweryn** [comment]
I have one request, when adding tests please use JUnit – I've started migrating to it from Spock as it's not supported for Android anymore.
